Working CBF with bdk master branch
thunderbiscuit/bdk-ffi pull request #6
Opened 2023-04-14 12:51 UTC by andreasgriffin

see https://github.com/bitcoindevkit/bdk-ffi/pull/207#issuecomment-1507486619

2023-05-02 18:01 UTC, thunderbiscuit requested changes
Looks good! Do you mind running `cargo fmt` so as to clean up the few syntax issues?

Also, I'm trying to test locally on testnet but I don't have a peer address I can use in the `address` field of the config. Do you mind sharing one if you have any, or let me know how you tested this? I think the previous implementation went to some default peer if none was provided, but here we'll need at least one.

2023-05-02 18:01 UTC, thunderbiscuit commented on bdk-ffi/src/blockchain.rs
> +    Cbf { config: CompactFiltersConfig },
Let's call it `CompactFilters` so as to keep in line with the naming of the other fields (which reflect the enum variant in the `AnyBlockchainConfig` type).

```rust
/// CompactFilters
CompactFilters { config: CompactFiltersConfig },
```

2023-05-02 18:01 UTC, thunderbiscuit commented on bdk-ffi/src/blockchain.rs
> +                }
As we prepare this PR for final merge we should consider expanding the full `peers: Vec<BitcoinPeerConfig>` type.

2023-05-02 18:01 UTC, thunderbiscuit commented on bdk-ffi/src/blockchain.rs
> +                }
For now I think this is good. I just want to keep track of it.

2023-05-02 18:01 UTC, thunderbiscuit commented on bdk-ffi/src/blockchain.rs
> +}
Let's add the inline docs from the [Rust docs](https://docs.rs/bdk/0.27.1/bdk/blockchain/compact_filters/struct.CompactFiltersBlockchainConfig.html) on the `CompactFilterConfig` type.

2023-05-02 18:01 UTC, thunderbiscuit commented on bdk-ffi/src/bdk.udl
> +  Cbf(CompactFiltersConfig config);
See comment below about renaming.

2023-05-06 16:49 UTC, andreasgriffin commented
> Also, I'm trying to test locally on testnet but I don't have a peer address I can use in the `address` field of the config. Do you mind sharing one if you have any, or let me know how you tested this? I think the previous implementation went to some default peer if none was provided, but here we'll need at least one.

Hi,  I tested it all with a local regtest/testnet/mainnet node by enabling (bitcoin.conf)
```
peerblockfilters=1
blockfilterindex=1
```
Regtest is easiest, because it is fast.  Testnet needs a lot of time (way more than mainnet) to sync (and sometimes crashes in the middle). The bdk CBF implementation is clearly still "experimental".


I'll take a look at the requested changes soon.

2023-06-11 11:54 UTC, andreasgriffin commented
It seems the blockchain.broadcast method (for cbf) is defunct. 
![image](https://github.com/thunderbiscuit/bdk-ffi/assets/116060138/71a3e55f-a548-42d8-bf48-21a52fec5539)
The node does not receive the tx.  When I broadcast it via rpc or the [bitcoin p2p](https://github.com/andreasgriffin/bitcoin-p2p) messages, the tx is accepted in the nodes mempool.

2023-06-22 15:07 UTC, andreasgriffin commented
Hi  @thunderbiscuit :  Can you please update your master to the bitcoindevkit/master, so the changed files in the PR is useful.

2023-06-22 15:54 UTC, thunderbiscuit commented
I pulled the latest changes on `bdk-ffi/master` into my master and rebased this branch on that. It was a... total mess. I expect it will break this PR hard. I'm not sure if it's worth keeping up as a PR until we are really ready to put work into this (once bdk 1.0 is release with the compact block filters capability). Feel free to keep this PR open though! I just don't want to promise things I won't have resources for.

2023-06-22 15:56 UTC, thunderbiscuit commented
@andreasgriffin how do you feel about starting fresh and opening a PR on bdk-ffi directly from your fork and cbf branch? This would allow you to have better control over the commit history, and that way you can keep it up to date with `master` on bdk-ffi if you have the resources/need to do that.

Let me know if that's something you'd like to take on; once you open the PR I can close bitcoindevkit/bdk-ffi#207 in favour of yours.

2023-06-22 17:01 UTC, andreasgriffin commented
@thunderbiscuit : Yes opening a PR on bdk-ffi directly  (even though it won't get merged before bdk 1.0), is better. I'll do that.

> (once bdk 1.0 is release with the compact block filters capability)

Do you have any idea, when a CBF directory will be added to https://github.com/bitcoindevkit/bdk/tree/master/crates

2023-06-22 17:01 UTC, closed without merging

2023-06-22 17:26 UTC, thunderbiscuit commented
No unfortunately I don't have a good time estimate. I know it's on the roadmap, but the 1.0 has taken a lot more work than initially anticipated so I don't really know where they stand with the CBF just yet.

Feel free to ask on the #development channel of the Discord server! Are you with us yet? I hope so!

2023-06-22 17:37 UTC, andreasgriffin commented
Thanks, I will ask on the #development channel.